# permissions for end users to view cyndipipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cyndipipeline-viewer-role
rules:
- apiGroups:
  - cyndi.cloud.redhat.com
  resources:
  - cyndipipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cyndi.cloud.redhat.com
  resources:
  - cyndipipelines/status
  verbs:
  - get
